import { run } from "./_services/databaseService";
import NavBar from "./UI/NavBar";
import SideBar from "./UI/SideBar";
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + " min-h-screen"}>
        <NavBar />
        <div className="flex flex-row min-h-screen">
          <div className="bg-primary p-3 hidden lg:block">
            <SideBar />
          </div>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
